build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-9-release-golang-1.19-openshift-4.13
images:
- dockerfile_path: Dockerfile
  to: log-file-metric-exporter
- dockerfile_path: Dockerfile.src
  to: log-file-metric-exporter-src
promotion:
  name: 5.y
  namespace: logging
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.14"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: test
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: openshift-ci
    product: ocp
    timeout: 1h0m0s
    version: "4.12"
  steps:
    test:
    - as: test
      commands: make test
      from: log-file-metric-exporter-src
      resources:
        requests:
          cpu: 100m
      timeout: 15m0s
    workflow: generic-claim
zz_generated_metadata:
  branch: main
  org: ViaQ
  repo: log-file-metric-exporter
